[workspace]

members = [
    "ck3-tiger",
    ".",
]

[package]
name = "tiger-lib"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1"
as-any = "0.3.0"
bitflags = "2.3.3"
encoding = "0.2"
fnv = "1"
image = "0.24"
lazy_static = "1"
once_cell = "1.18.0"
png = "0.17.6"
strum = "0.25"
strum_macros = "0.25"
thiserror = "1"
unicode-width = "0.1.9"
walkdir = "2"
ansi_term = "0.12.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "criterion"
harness = false

[profile.bench]
debug = true
