on:
  push:
    branches:
      - main
      - doc-test

name: Documentation

# Write access to the Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# allow only one action at a time to write to the Github Pages
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build documentation
        run: cargo doc --features "ck3 vic3" --no-deps --document-private-items

      - name: Create index.html
        shell: bash
        run: echo '<meta http-equiv="refresh" content="0; url=tiger_lib">' >target/doc/index.html

      - name: Fix permissions
        run: |
          chmod -c -R +rX "target/doc" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "target/doc"

  deploy:
    name: Deploy to Github Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
